#!/usr/bin/perl

use Socket;

my $server_port=4999;
my $BATCHSIZE=16;

# make the socket
socket(SERVER, PF_INET, SOCK_STREAM, getprotobyname('tcp'));

# so we can restart our server quickly
setsockopt(SERVER, SOL_SOCKET, SO_REUSEADDR, 1);

# build up my socket address
my $my_addr = sockaddr_in($server_port, INADDR_ANY);
bind(SERVER, $my_addr)
    or die "Couldn't bind to port $server_port : $!\n";

# establish a queue for incoming connections
listen(SERVER, SOMAXCONN)
    or die "Couldn't listen on port $server_port : $!\n";

# accept and process connections
$item=0;
$remaining=1;
$shutdown=0;
open(PROGRESS,">> ./progress");
open(OUTPUT,">> ./final.output");
open(ERROR,">> ./error.output");
$SIG{INT} = \&catch_int;  # best strategy
$input=<stdin>;
while ($remaining){
  $address=accept(CLIENT, SERVER);
  next unless $address;
  ($cDomain, $cPort, $cAdd) = unpack('S n a4 x8', $address);
  $cHost=join('.',unpack('C4', $cAdd));
#  print "Connect from $cHost\n";

  $got_response=0;
  $send_query=0;
  $ident="noid";
# Read from client
#
  while(<CLIENT>){
# print $_;
    if (/^RESULTS /){
      $lines=0;
      ($COMMAND,$seq)=split;
      chomp $seq;
      while(! $got_response){
        $_=<CLIENT>;
        if (/^DONE$/){
          if (defined $job{$seq}){
            $sequences=join ",",@{$job{$seq}->{list}};
            printf PROGRESS "%s %s %d %d %d %d\n", 
		$sequences,$ident,time-$job{$seq}->{start},
		$lines,time,$job{$seq}->{len};
            printf "%-8d seq:%25s host:%-16s  time:%-4ds lines: %d\n", 
		$processed, $sequences,$ident,
		time-$job{$seq}->{start},$lines;
            $processed+=$job{$seq}->{count};
            delete $job{$seq};
          }
          else{
            print stderr "Unexpect report from $cHost:$ident for $seq\n";
          }
          print CLIENT "RECEIVED $seq\n";
          $got_response=1;
        }
        else{ 
          print OUTPUT;
          $lines++;
        }
        $got_response=1 unless $_;  # catch the edge case
      } # While for response
    }   #
    elsif (/^IDENT /){
      ($COMMAND,$ident)=split;
    }
    elsif (/^NEXT$/){
      $send_query=1;
    }
    else{
      print stderr "Recieved unusual response from $cHost: $_";
    }
  }
#
#
# Do we need to send a query?  Make sure we aren't in a shutdown.
#
  if ($send_query && $shutdown==0){
    $next=1;
    $header=0;
    $length=0;
    $batch=0;
    $sent=[];
    while($next eq 1){
      last if ($input=~/^>/ && $batch==$BATCHSIZE);      
      last if eof(stdin);
      $input=~s/\r//;
      print CLIENT $input;
      $length+=length $input;
      if ($input=~/^>/){
        ($bl,$header,$rest)=split /[> \r\n]/,$input;
        push @{$sent}, $header;
        $batch++;
      }
      $input=<stdin>;
    }
    if ($header ne 0){
      $job{$header}->{start}=time;
      $job{$header}->{len}=$length;
      $job{$header}->{list}=$sent; 
      $job{$header}->{count}=$batch; 
    }
    print "Sent: $item:$header to $cHost:$ident:$length\n";
    $item++;
  }
  close CLIENT;
  if ( eof(stdin) || $shutdown){
    $shutdown=1;
    $remaining=keys %job;
    print "Draining: $remaining remaining connections\n";
  }
}

close PRROGRESS;
close OUTPUT;
close ERROR;
close SERVER ;

sub catch_int {
  my $signame = shift;
  if ($shutdown){
    close PRROGRESS;
    close OUTPUT;
    close ERROR;
    close SERVER ;
    close PROGRESS;
    print "Exiting\n";
    exit;
  }
  else{
    $shutdown=1;
    $remaining=keys %sent;
    print "Shutting down\n";
    print "Draining: $remaining remaining connections\n";
  }
}

