#!/bin/ksh
SERVER=$1
PORT=$2
TIMEOUT=9
PATH=$TMPDIR:$PATH:$BASE/bin

ID="testhost"

send_response () {
  echo "$MESS"
  echo "IDENT $ID" > message
  echo "MESSAGE $MESS" >> message
  echo "RESULTS $STEP" >> message
  cat sample.out >> message
  echo "DONE" >> message
  echo "NEXT" >> message 
  (cat message)|netcat -w $TIMEOUT $SERVER $PORT > response
  grep -v RECEIVED response  > rmess
  STEP=$(grep 'STEP' rmess|sed 's/STEP: //')
}

just_request () {
  echo "$MESS"
  (echo "IDENT $ID";echo "MESSAGE $MESS";echo "NEXT")|netcat $SERVER $PORT > rmess
  STEP=$(grep 'STEP' rmess|sed 's/STEP: //')
}

send_error () {
  echo "$MESS"
  (echo "IDENT $ID";echo "MESSAGE $MESS";echo "ERROR $STEP";echo "NEXT")|netcat $SERVER $PORT > response
  STEP=$(grep 'STEP' response|sed 's/STEP: //')
}

MESS="Request" just_request
MESS="This should work" send_response
MESS="This should work" send_response
echo "Force a retry (sleep)"
sleep $TIMEOUT
MESS="This should fail and retry." send_response
MESS="This should work" send_response
MESS="This should work" send_response

echo "Force a max retry (long sleep)"
sleep $TIMEOUT
MESS="This should fail." send_response
sleep $TIMEOUT
MESS="This should fail with max retry" send_response
MESS="This should work" send_response
MESS="This should work" send_response
MESS="This should work" send_response

MESS="Send an error message" send_error

MESS="Next to last request from test client.  Hit ctl-c to test shutdown" send_response
sleep 4
MESS="Last message" send_response

